# Generated by Django 5.2.13 on 2026-04-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('move_type', models.CharField(choices=[('home', 'Home Relocation'), ('office', 'Office Relocation')], max_length=20)),
                ('pickup_location', models.CharField(max_length=255)),
                ('destination_location', models.CharField(max_length=255)),
                ('property_size', models.CharField(choices=[('bedsitter', 'Bedsitter'), ('1_bedroom', '1 Bedroom'), ('2_bedroom', '2 Bedroom'), ('3_bedroom', '3 Bedroom'), ('office_small', 'Small Office'), ('office_medium', 'Medium Office')], max_length=30)),
                ('needs_packing', models.BooleanField(default=False)),
                ('needs_unpacking', models.BooleanField(default=False)),
                ('estimated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
