# Generated by Django 5.2.13 on 2026-04-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='phone_number',
        ),
    ]
